export { default as App } from './App';
export { default as Login } from './acces/Login';
export { default as Header } from './components/header/Header';
export { default as Navbar } from './components/navbar/Navbar';
export { default as Buttons } from './components/navbar/components/Buttons';
export * from './constans/Index';
export * from './index';
export * from './main';
export { default as Inicio } from './pages/Inicio';
export { default as Dashboard } from './pages/dashboard/Dashboard';
export { default as Historial } from './pages/historial/Historial';
